name: artic-rabv
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
#  - artic=1.2.3
  - pip:
     - git+https://github.com/kirstyn/fieldbioinformatics.git@1.3.0-dev #egg=artic
     - medaka==1.8.1
     - pysam
     - seaborn
  -  git clone git@github.com:centre-for-virus-research/weeSAM.git
  - artic-network::rampart=1.2.0
  - snakemake-minimal=5.8.1
  #- datamash=1.1.0
  - tabix
  - artic-porechop=0.3.2pre
  - artic-tools=0.3.1
  - bcftools<=1.13
  - biopython=1.79
  - bwa=0.7.17
  - clint=0.5.1
  - htslib=1.12
  - longshot>=0.4.3
  - nanopolish=0.13.2
  - minimap2=2.24
  - multiqc=1.12
  - mafft=7.505
  - nomkl=1.0
  - pandas=1.4.2
  - pip
  - pysam=0.17.0
  - pytest=7.1.2
  - python>=3.8
  - pyvcf=0.6.8
  - samtools=1.12
  - tqdm=4.64.0
  - snp-sites=2.5.1
  - pyfaidx =0.6.0
  - muscle=5.1
